name: task_assesment
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.1
  flutter_local_notifications: ^18.0.1
  hive_ce: ^2.10.0
  hive_ce_flutter: ^2.2.0
  equatable: ^2.0.7
  fpdart: ^1.1.1
  battery_plus: ^6.2.1
  flutter_background_service: ^5.1.0
  collection: ^1.19.0
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_ce_generator: ^1.8.2

flutter:
  uses-material-design: true

